spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      url: jdbc:mysql://119.23.190.71:3306/db_tx?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      max-active: 5
      # log4j  log4j2 slf4j (logback)
      filters: wall,stat, slf4j
      #  监控配置
      web-stat-filter:
        # 开启后台性能检测
        enabled: true
        # 访问接口就是对数据库操作
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin